# Intro python data science
## Práctica 04: numpy ndarray

Vamos a ver cómo:
* Punto 1: Crear ndarrays en python
* Punto 2: Operar entre columnas
* Punto 3: Seleccionar elementos

# Punto 1:

In [2]:
# importar numpy
import numpy as np

In [1]:
# crear lista con numeros primos
numeros_primos = [2,3,5,7,11,13,17,19,23,29]
numeros_primos

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

In [3]:
# crear array a partir de lista
array_primos = np.array(numeros_primos)
array_primos

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [4]:
# crear arrays con ceros o cómo inicializar un arreglo de numpy
array_zeros = np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
# crear arrays con números
array_numeros = np.arange(10)
array_numeros

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# array con numeros sucesivos
array_pares = np.arange(0,20,2)
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# haciendo un reshape para dos dimensiones
# Crear matriz de 2 filas y 5 columnas
array_pares.reshape(2, 5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

# Punto 2:

In [ ]:
# operaciones aritmeticas sobre np array 1-dimension y 2-dimension


In [ ]:
# multiplicar por 100


In [ ]:
# resta entre arrays


In [ ]:
# cuidado con la división entre cero


In [ ]:
# métodos asociados a estadística
# suma


In [ ]:
# promedio


In [ ]:
# varianza


In [ ]:
# como ordenar un np array


In [ ]:
# orden ascendente: de menor a mayor


In [ ]:
# orden descendente: de mayor a menor


# Punto 3:

In [ ]:
# Como seleccionar elements

In [ ]:
# Seleccionar un elemento

In [ ]:
# seleccionar el primer elemento


In [ ]:
# seleccionar algún otro elemento


In [ ]:
# Seleccionar varios elementos

In [ ]:
# seleccionar por fila


In [ ]:
# seleccionar por columna


In [ ]:
# Utilizar filter

In [ ]:
# conidicion para menores de 20


In [ ]:
# filtrar menores de 20


# Gracias!
## Espero que te lleves algo útil de este notebook 😀

Para más videos de programación para ciencia de datos

https://www.youtube.com/c/RafaGonzalezGouveia/

Si quieres realizar alguno de los cursos online de pago, ve a:

https://cursos.gonzalezgouveia.com